---
title: "Cost of Living in Toronto For low-income household"
output: pdf_document
date: "2023-04-06"
author: Jin Long Cao
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# install.packages('plotrix')
library(plotrix)
```

## intro
Scenario 3 is the median income should be used as a comparator
```{r import_Data}
with_subsidies <- read.csv("Data/2022 Income Scenario - With Subsidies.csv")
test <- read.csv("Data/2022 Income Scenario - With Subsidies.csv")
y <- read.csv("Data/2022 Income Scenario - Without Subsidies, Average Rent.csv")
z <- read.csv("Data/2022 Income Scenario - Without Subsidies, Market Rent.csv")
```


## cleaning
The current data are all character types which is difficult to manipulate. Part of the cleaning process it to turn all values numeric.
```{r char_to_num} 
# This function:
# changes null values/empty quotes to 0
# remove "$" and "," and turn strings to numeric
# Change x% to decimal
char_to_num <- function(column) {
  counter <- 1 
  for (i in column){
    if (i == "" || i == " " || i == "   "){ ## Changing null values to $0
      column[counter] <- as.numeric(0)
    } else if (grepl("\\$", i)){ ## Character variable( dollar amount) to numeric
      column[counter] = as.numeric(gsub("\\$", "", gsub(",", "", i)))
    } else { #percentage to a decimal
      column[counter] = as.numeric(gsub("%", "", i))/100
    }
  counter <- counter + 1
  }
  return(column)
}
```



```{r}
with_subsidies$Scenario.1..Family.of.Four..Ontario.Works = char_to_num(with_subsidies$Scenario.1..Family.of.Four..Ontario.Works)

with_subsidies$Scenario.2..Family.of.Four..Full.Time.Minimum.Wage.Earner = char_to_num(with_subsidies$Scenario.2..Family.of.Four..Full.Time.Minimum.Wage.Earner)

with_subsidies$Scenario.3..Family.of.Four..Median.Income = char_to_num(with_subsidies$Scenario.3..Family.of.Four..Median.Income)

with_subsidies$Scenario.4..Single.Parent.Household.with.2.Children..Ontario.Works = char_to_num(with_subsidies$Scenario.4..Single.Parent.Household.with.2.Children..Ontario.Works)

with_subsidies$Scenario.5..One.person.Household..Ontario.Works = char_to_num(with_subsidies$Scenario.5..One.person.Household..Ontario.Works)

with_subsidies$Scenario.6..One.Person.Household..Ontario.Disability.Support.Program = char_to_num(with_subsidies$Scenario.6..One.Person.Household..Ontario.Disability.Support.Program)

with_subsidies$Scenario.7..One.Person.Household..Old.Age.Security..Guaranteed.Annual.Income.Supplement = char_to_num(with_subsidies$Scenario.7..One.Person.Household..Old.Age.Security..Guaranteed.Annual.Income.Supplement)

with_subsidies$Scenario.8..Married.Couple..Ontario.Disability.Support.Program = char_to_num(with_subsidies$Scenario.8..Married.Couple..Ontario.Disability.Support.Program)

with_subsidies$Scenario.9..Single.Person.Household..Full.Time.Minimum.Wage.Earner = char_to_num(with_subsidies$Scenario.9..Single.Person.Household..Full.Time.Minimum.Wage.Earner)


# Scenarios <- list(with_subsidies$Scenario.1..Family.of.Four..Ontario.Works, with_subsidies$Scenario.2..Family.of.Four..Full.Time.Minimum.Wage.Earner, with_subsidies$Scenario.3..Family.of.Four..Median.Income, with_subsidies$Scenario.4..Single.Parent.Household.with.2.Children..Ontario.Works, with_subsidies$Scenario.5..One.person.Household..Ontario.Works, with_subsidies$Scenario.6..One.Person.Household..Ontario.Disability.Support.Program, with_subsidies$Scenario.7..One.Person.Household..Old.Age.Security..Guaranteed.Annual.Income.Supplement, with_subsidies$Scenario.8..Married.Couple..Ontario.Disability.Support.Program, with_subsidies$Scenario.9..Single.Person.Household..Full.Time.Minimum.Wage.Earner)
# 
# Unable to do above with for loop due to address accessibility 
# for (i in Scenarios){
#   print(i)
# }
```


## Identifying the main cost drivers













